version: "3"

services:

   etracs-server:
      volumes:
         ## mounted RPTIS services build 2.5.03.02.01 
         - ./dev_modules/rptis-2.5.03.02.01:/services/modules/rptis

         - ./dev_modules/bpls:/services/modules/bpls
         - ./dev_modules/admin:/services/modules/admin
         - ./dev_modules/treasury:/services/modules/treasury
