version: "3"

services:

  comis-server:
    image: ramesesinc/enterprise-common-server:255.05.001
    container_name: comis-server
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports:
      - "8074:8070"
    volumes:
      - ../../_res/connections:/enterprise/connections/ext
      - ../../_custom/datasources/comisds:/services/datasources/mainds
      - ../../_custom/output:/apps/server/output

      - ./server-modules:/enterprise/modules
      - ./module-client/reports:/apps/server/templates
